# This file was generated by GoReleaser. DO NOT EDIT.
cask "ramify" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "ccafa030491af693bd4976b558ff19c4d974176f33ff5ff3bdc916ae2b2897f8"
      url "https://github.com/alexeyu/ramify/releases/download/v#{version}/ramify_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "82623c34e026e017d461d47bd042f70a4d72087ec7a222dcbb62a5da6f00f098"
      url "https://github.com/alexeyu/ramify/releases/download/v#{version}/ramify_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "13cf594f5d9fb848bdd9889dd9f7d066243ee800390ef1ec594329f0f336df37"
      url "https://github.com/alexeyu/ramify/releases/download/v#{version}/ramify_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6393b1fffc7eed5fa870981738afbff0bb9302e0697388e1feeb766f148be786"
      url "https://github.com/alexeyu/ramify/releases/download/v#{version}/ramify_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ramify"
  desc "Concurrent fan-out file uploader for FTP/FTPS/SFTP endpoints"
  homepage "https://github.com/alexeyu/ramify"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ramify"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ramify"]
    end
  end

  # No zap stanza required

end
