# This file was generated by GoReleaser. DO NOT EDIT.
cask "uploadfun" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "a6c87745fd131dee9b63c0399720277795e6393d2c83bc0b7144011e72994cc3"
      url "https://github.com/alexeyu/uploadfun/releases/download/v#{version}/uploadfun_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1f0514406dbccc8ad235e744842fa4992b63ca4cdefee0b4478a6adfe97cc7e3"
      url "https://github.com/alexeyu/uploadfun/releases/download/v#{version}/uploadfun_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "89edd3967f00090027ef4d0e59a095a091bdc8f06206f2d86643b05971c71436"
      url "https://github.com/alexeyu/uploadfun/releases/download/v#{version}/uploadfun_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aa4942c7d5fd6cdb7a3eec6625d101486a03d5730d21d27494c4705c52b67a25"
      url "https://github.com/alexeyu/uploadfun/releases/download/v#{version}/uploadfun_#{version}_linux_arm64.tar.gz"
    end
  end

  name "uploadfun"
  desc "Concurrent fan-out file uploader for FTP/FTPS/SFTP endpoints"
  homepage "https://github.com/alexeyu/uploadfun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "uploadfun"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/uploadfun"]
    end
  end

  # No zap stanza required

end
