# This file was generated by GoReleaser. DO NOT EDIT.
cask "uploadfun" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "181837118ade54a395fec93d4329aea37dd87cfaf6713162b70464db91d72ff9"
      url "https://github.com/alexeyu/uploadfun/releases/download/v#{version}/uploadfun_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7d74caa7afa18a4f577b8f6f431e576c1a2ad9182b789d241327e7c1e19f6042"
      url "https://github.com/alexeyu/uploadfun/releases/download/v#{version}/uploadfun_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d3fb4560e257c2ba493bee17f68178ec263356702692290ca6a27765183d342e"
      url "https://github.com/alexeyu/uploadfun/releases/download/v#{version}/uploadfun_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "57ec8c33dc6b105ee8193b515a7509060fc871e92a5830c77822e9c3667149b1"
      url "https://github.com/alexeyu/uploadfun/releases/download/v#{version}/uploadfun_#{version}_linux_arm64.tar.gz"
    end
  end

  name "uploadfun"
  desc "Concurrent fan-out file uploader for FTP/FTPS/SFTP endpoints"
  homepage "https://github.com/alexeyu/uploadfun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "uploadfun"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/uploadfun"]
    end
  end

  # No zap stanza required

end
